CPPFLAGS= -Wall -Wextra -pedantic

all:
	# Insert command to compile the code and generate executable
	g++ -std=c++11 Map.hpp
	g++ -std=c++11 minimal.cpp -o minimal
	g++ -std=c++11 test.cpp -o test
run:
	# Insert command to run the executable
	./minimal
	./test
checkmem:
	# Insert command to run the executable with valgrind

clean:
	# Insert command to clean object files, executables
	rm minimal test
