CPPFLAGS= -Wall -Wextra -pedantic

all:
	# Insert command to compile the code and generate executable
	g++ -std=c++11 Map.hpp
	g++ -std=c++11 minimal.cpp -o minimal
run:
	# Insert command to run the executable

checkmem:
	# Insert command to run the executable with valgrind

clean:
	# Insert command to clean object files, executables
